//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v{{GENERATOR_VERSION}}
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: {{GENERATED_AT}}
//     Template: {{TEMPLATE_NAME}}
//     Target: {{RESULT_TYPE}} ({{TARGET_FRAMEWORK}})
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;
using ZeroResult.Helpers;

namespace ZeroResult;

public {{Modifier}} partial struct {{ResultType}}<T, TError>
    where TError : IError
{
    /// <summary>
    /// Gets the successful value if the result is successful.
    /// Throws an exception if the result is a failure.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when accessing Value on a failed result.</exception>
    public readonly T Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_isSuccess == false)
                ThrowHelper.ThrowInvalidAccess("Cannot access Value on a failed result.");

            Debug.Assert(_value is not null, "Value should not be null when accessing Value on a success.");

            return _value;
        }
    }

    /// <summary>
    /// Gets the error if the result is a failure.
    /// Throws an exception if the result is successful.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when accessing Error on a successful result.</exception>
    public readonly TError Error
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_isSuccess)
                ThrowHelper.ThrowInvalidAccess("Cannot access Error on a successful result.");

            Debug.Assert(_error is not null, "Error should not be null when accessing Error on a failure.");

            return _error;
        }
    }
}
